describe('選單', () => 
{
    beforeEach(() => {
        cy.viewport(288, 640)
    })
    it('訪問頁面', () => {
        cy.visit('/m-frontend')
    })
    it('開啟選單', () => {
        cy.get('.ivu-icon')
            .click()
    })
    it('項目檢查', () => {
        cy.get(':nth-child(1) > .menu__item__title')
            .contains('建立車籍')
        cy.get(':nth-child(2) > .menu__item__title')
            .contains('剩餘車位')
        cy.get(':nth-child(3) > .menu__item__title')
            .contains('移入車位')
        cy.get(':nth-child(4) > .menu__item__title')
            .contains('車輛查詢')
        cy.get(':nth-child(5) > .menu__item__title')
            .contains('車輛作業')
        cy.get(':nth-child(6) > .menu__item__title')
            .contains('車位查詢')
        cy.get(':nth-child(7) > .menu__item__title')
            .contains('建立車位')
        cy.get(':nth-child(8) > .menu__item__title')
            .contains('出庫')
        cy.get(':nth-child(9) > .menu__item__title')
            .contains('車輛保養')
        cy.get(':nth-child(10) > .menu__item__title')
            .contains('設定')
        cy.get('.menu__footer__title')
            .contains('登出')
    })
    it('連結檢查', () => {
        cy.get(':nth-child(1) > .menu__item__title')
            .click()
        cy.get('.title')
            .contains('建立車籍')
        cy.get('.navbar__menu-icon > .ivu-icon')
            .click()
        cy.get(':nth-child(2) > .menu__item__title')
            .click()
        cy.get('.title')
            .contains('剩餘車位')
        cy.get('.navbar__menu-icon > .ivu-icon')
            .click()
        cy.get(':nth-child(3) > .menu__item__title')
            .click()
        cy.get('.title')
            .contains('移入車位')
        cy.get('.navbar__menu-icon > .ivu-icon')
            .click()
        cy.get(':nth-child(4) > .menu__item__title')
            .click()
        cy.get('.title')
            .contains('車輛查詢')
        cy.get('.navbar__menu-icon > .ivu-icon')
            .click()
        cy.get(':nth-child(5) > .menu__item__title')
            .click()
        cy.get('.title')
            .contains('車輛作業')
        cy.get('.navbar__menu-icon > .ivu-icon')
            .click()
        cy.get(':nth-child(6) > .menu__item__title')
            .click()
        cy.get('.title')
            .contains('車位查詢')
        cy.get('.navbar__menu-icon > .ivu-icon')
            .click()
        cy.get(':nth-child(7) > .menu__item__title')
            .click()
        cy.get('.title')
            .contains('建立車位')
        cy.get('.navbar__menu-icon > .ivu-icon')
            .click()
        cy.get(':nth-child(8) > .menu__item__title')
            .click()
        cy.get('.title')
            .contains('出庫')
        cy.get('.navbar__menu-icon > .ivu-icon')
            .click()
        cy.get(':nth-child(9) > .menu__item__title')
            .click()
        cy.get('.title')
            .contains('車輛保養')
        cy.get('.navbar__menu-icon > .ivu-icon')
            .click()
        cy.get(':nth-child(10) > .menu__item__title')
            .click()
        cy.get('.title')
            .contains('設定')
    })
})