describe('移入車位', () => {
    beforeEach(() => {
        cy.viewport(288, 640)
    })
    it('訪問頁面', () => {
        cy.visit('/m-frontend/move-in')
    })
    it('介面檢查', () => {
        cy.get('.mb-20 > .ivu-form-item-label')
            .contains('生產 / 底盤編號、QRcode')
        cy.get('.mt-10 > .ivu-form-item-label')
            .contains('車位識別碼')
    })
    it('移入車位', () => {
        cy.get('.mb-20 > .ivu-form-item-content > .ivu-input-wrapper > .ivu-input')
            .type('e2eTest')
            .type('{enter}')
        cy.get('#ps-input')
            .type('e2eTest_PS')
        cy.get('.btn')
            .click()
    })
    it('查詢車位', () => {
        cy.viewport(1366, 768)
        cy.visit('/frontend')
        cy.get('#menu-item-1 > .c-menu__items__title')
            .click()
        cy.get('.ivu-input')
            .type('e2eTest_PS')
        cy.get('.ivu-btn-primary')
            .click()
        cy.get('.ivu-table-body > table > .ivu-table-tbody > :nth-child(1) > :nth-child(1)')
            .contains('e2eTest_PS')
        cy.get('.ivu-table-body > table > .ivu-table-tbody > :nth-child(1) > :nth-child(4)')
            .contains('e2eTest')
    })
})