describe('車輛作業', () => {
    beforeEach(() => {
        cy.viewport(288, 640)
    })
    it('訪問頁面', () => {
        cy.visit('/m-frontend/vehicle/operation')
    })
    it('介面檢查', () => {
        cy.get('.title')
            .contains('車輛作業')
        cy.get('.ivu-form-item-label')
            .contains('生產編號')
    })
    it('查詢', () => {
        cy.get('.ivu-form-item-content > .ivu-input-wrapper > .ivu-input')
            .type('eTest')
        cy.get('.footer > :nth-child(2)')
            .click()
        cy.get('.id-list__item')
            .click()
    })
    it('查詢結果介面檢查', () => {
        cy.get(':nth-child(1) > .info-result__item__label')
            .contains('生產編號')
        cy.get(':nth-child(1) > .info-result__item__content')
            .contains('e2eTest')
        cy.get(':nth-child(2) > .info-result__item__label')
            .contains('底盤編號')
        cy.get(':nth-child(2) > .info-result__item__content')
            .contains('e2eTest')
        cy.get(':nth-child(4) > .operation-btn__label')
            .contains('PDI / 洗車')
        cy.get(':nth-child(5) > .operation-btn__label')
            .contains('隔熱紙')
        cy.get(':nth-child(6) > .operation-btn__label')
            .contains('配件')
        cy.get(':nth-child(7) > .operation-btn__label')
            .contains('美容 / 鍍膜')
        cy.get('.footer > .btn--outline')
            .contains('返回')
    })
})