describe('車輛保養', () => {
    beforeEach(() => {
        cy.viewport(288, 640)
    })
    it('訪問頁面', () => {
        cy.visit('/m-frontend/vehicle/maintenance')
    })
    it('介面檢查', () => {
        cy.get('.title')
            .contains('車輛保養')
        cy.get('.ivu-form-item-label')
            .contains('生產編號')
    })
    it('查詢', () => {
        cy.get('.ivu-form-item-content > .ivu-input-wrapper > .ivu-input')
            .type('eTest')
        cy.get('.footer > :nth-child(2)')
            .click()
        cy.get('.id-list__item')
            .click()
    })
    it('查詢結果介面檢查', () => {
        cy.get(':nth-child(1) > .info-result__item__label')
            .contains('生產編號')
        cy.get(':nth-child(1) > .info-result__item__content')
            .contains('e2eTest')
        cy.get(':nth-child(2) > .info-result__item__label')
            .contains('底盤編號')
        cy.get(':nth-child(2) > .info-result__item__content')
            .contains('e2eTest')
        cy.get(':nth-child(4) > .maintain-btn__label')
            .contains('車輛維護')
        cy.get(':nth-child(5) > .maintain-btn__label')
            .contains('剎車油')
        cy.get(':nth-child(6) > .maintain-btn__label')
            .contains('機油')
        cy.get(':nth-child(7) > .maintain-btn__label')
            .contains('尿素')
        cy.get('.footer > .btn--outline')
            .contains('返回')
    })
})