describe('帳號', () => {
    it('訪問頁面', () => {
        cy.visit('/frontend/account')
        cy.get('.m-system-config')
            .should('be.visible')
    })
    it('介面元件初始', () => {
        cy.get('.panal__title')
            .contains('帳號資訊')
        cy.get('.panal__title')
            .contains('帳號設定')
        cy.get('.panal__items')
            .contains('使用者名稱')
        cy.get('.panal__items')
            .contains('名字')
        cy.get('.panal__items')
            .contains('姓氏')
        cy.get('.panal__items')
            .contains('電子郵件')
        cy.get('.panal__items')
            .contains('變更密碼')
        cy.get('.panal__items')
            .contains('語言')
    })
    it('變更密碼介面初始', () => {
        cy.get('.panal__items__set-btn')
            .click()
        cy.get('.ivu-modal-header')
            .contains('變更密碼')
        cy.get('.ivu-form > :nth-child(1)')
            .contains('舊密碼')
        cy.get('.ivu-form > :nth-child(3)')
            .contains('新密碼')
        cy.get('.ivu-form > :nth-child(5)')
            .contains('確認密碼')
        cy.get('.ivu-btn-primary')
            .should('has.attr', 'disabled', 'disabled')
    })
    it('未輸入密碼提醒', () => {
        cy.get(':nth-child(4) > .ivu-form-item-content > .ivu-poptip > .ivu-poptip-rel > .w-250 > .ivu-input')
            .click()
        cy.get('.ivu-modal-body')
            .click()
        cy.get('.ivu-form-item-error-tip')
            .contains('請輸入密碼')
    })
    it('密碼少於8碼提醒', () => {
        cy.get(':nth-child(4) > .ivu-form-item-content > .ivu-poptip > .ivu-poptip-rel > .w-250 > .ivu-input')
            .type('1234')
        cy.get('.ivu-modal-body')
            .click()
        cy.get('.ivu-form-item-error-tip')
            .contains('密碼不得少於8碼')
    })
    it('密碼超過16碼提醒', () => {
        cy.get(':nth-child(4) > .ivu-form-item-content > .ivu-poptip > .ivu-poptip-rel > .w-250 > .ivu-input')
            .clear()
            .type('11111111111111111')
        cy.get('.ivu-modal-body')
            .click()
        cy.get('.ivu-form-item-error-tip')
            .contains('密碼不得大於16碼')
    })
    it('密碼至少需一英文字提醒', () => {
        cy.get(':nth-child(4) > .ivu-form-item-content > .ivu-poptip > .ivu-poptip-rel > .w-250 > .ivu-input')
            .clear()
            .type('12345678')
        cy.get('.ivu-modal-body')
            .click()
        cy.get('.ivu-form-item-error-tip')
            .contains('密碼至少輸入一個英文字')
    })
    it('確認密碼欄位驗證機制', () => {
        cy.get(':nth-child(4) > .ivu-form-item-content > .ivu-poptip > .ivu-poptip-rel > .w-250 > .ivu-input')
            .clear()
            .type('Fuco1234')
        cy.get('.ivu-modal-body')
            .click()
        cy.get(':nth-child(6) > .ivu-form-item-content > .ivu-poptip > .ivu-poptip-rel > .w-250 > .ivu-input')
            .type('Fuco4321')
        cy.get('.ivu-modal-body')
            .click()
        cy.get('.ivu-form-item-error-tip')
            .contains('新舊密碼不同')
    })
    it('重設確認值清空', () => {
        cy.get('.ivu-form-item-content > .w-250 > .ivu-input')
            .clear()
            .type('Fuco1234')
        cy.get(':nth-child(4) > .ivu-form-item-content > .ivu-poptip > .ivu-poptip-rel > .w-250 > .ivu-input')
            .clear()
            .type('Fuco1234')
        cy.get('.ivu-modal-body')
            .click()
        cy.get(':nth-child(6) > .ivu-form-item-content > .ivu-poptip > .ivu-poptip-rel > .w-250 > .ivu-input')
            .clear()
            .type('Fuco1234')
        cy.get('.ivu-modal-body')
            .click()
        cy.get('.ivu-btn-default')
            .click()
        cy.get('.ivu-form-item-content > .w-250 > .ivu-input')
            .should('be.empty')
        cy.get(':nth-child(4) > .ivu-form-item-content > .ivu-poptip > .ivu-poptip-rel > .w-250 > .ivu-input')
            .should('be.empty')
        cy.get(':nth-child(6) > .ivu-form-item-content > .ivu-poptip > .ivu-poptip-rel > .w-250 > .ivu-input')
            .should('be.empty')
    })
    it('關閉', () => {
        cy.get('.ivu-modal-close > .ivu-icon')
            .click()
        cy.get('.ivu-modal-header')
            .should('not.be.visible')
    })
})