describe('登入介面', () => {
    it('訪問頁面', () => {
        cy.visit('/login')
    })
    it('沒有輸入帳密是否顯示錯誤', () => {
        cy.get('.btn__signin')
            .click()
        cy.get('.ivu-modal-confirm-body').contains('div', '請輸入帳號')
        cy.get('.ivu-modal-confirm-footer > .ivu-btn')
            .click()
    })
    it('沒有輸入密碼是否顯示錯誤', () => {
        cy.get(':nth-child(1) > .input')
            .type('atoll')
        cy.get('.btn__signin')
            .click()
        cy.get('.ivu-modal-confirm-body').contains('div', '請輸入密碼')
        cy.get('.ivu-modal-confirm-footer > .ivu-btn')
            .click()
    })
    it('輸入錯誤帳密是否顯示錯誤', () => {
        cy.get(':nth-child(1) > .input')
            .clear()
            .type('atoll')
        cy.get(':nth-child(2) > .input')
            .type('atoll')
        cy.get('.btn__signin')
            .click()
        cy.get('.ivu-modal-confirm-body').contains('div', '帳號或密碼錯誤')
        cy.get('.ivu-modal-confirm-footer > .ivu-btn')
            .click()
    })
    it('輸入正確帳密是否成功登入', () => {
        cy.get(':nth-child(1) > .input')
            .clear()
            .type('atoll')
        cy.get(':nth-child(2) > .input')
            .clear()
            .type('Fuco1234')
        cy.get('.btn__signin')
            .click()
        cy.get('.p-welcome')
            .should('be.visible')
    })
})