describe('車輛維護', () => {
    it('訪問頁面', () => {
        cy.visit('/frontend')
        cy.get('#menu-item-0 > .c-menu__items__title')
            .click()
        cy.get('.ivu-tabs-nav > :nth-child(4)')
            .click()
    })
    it ('表格介面檢查', () => {
        cy.get('.p-maintenance > .txt-color--error')
            .contains('所有保養項目將於 5 天前開始提醒')
        cy.get('.ivu-table-header > table > thead > tr > :nth-child(1)')
            .contains('生產編號')
        cy.get('.ivu-table-header > table > thead > tr > :nth-child(2)')
            .contains('底盤編號')
        cy.get('.ivu-table-header > table > thead > tr > :nth-child(3)')
            .contains('QRcode')
        cy.get('.ivu-table-header > table > thead > tr > :nth-child(4)')
            .contains('車輛維護')
        cy.get('.ivu-table-header > table > thead > tr > :nth-child(5)')
            .contains('剎車油')
        cy.get('.ivu-table-header > table > thead > tr > :nth-child(6)')
            .contains('機油')
        cy.get('.ivu-table-header > table > thead > tr > :nth-child(7)')
            .contains('尿素')
        cy.get('.ivu-table-header > table > thead > tr > :nth-child(8)')
            .contains('檢查中')
        cy.get('.ivu-table-header > table > thead > tr > :nth-child(9)')
            .contains('動作')
        cy.get(':nth-child(2) > .btn')
            .contains('匯出')
    })
})