import { dateFormat, startDate, endDate } from '../../../mixin.js'

describe('查詢', () => {
    it('訪問頁面', () => {
        cy.visit('/frontend')
        cy.get('#menu-item-0 > .c-menu__items__title')
            .click()
    })
    it('介面檢查', () => {
        cy.get('.l-view')
            .should('be.visible')
        cy.get('.ivu-tabs-tab-active')
            .contains('查詢')
        cy.get('.form-generate > .form-generate__content > :nth-child(1) > .form-generate__items__label')
            .contains('建立日期')
        cy.get('.form-generate > .form-generate__content > :nth-child(2) > .form-generate__items__label')
            .contains('生產/底盤編號、QRcode')
        cy.get('.form-generate > .form-generate__content > :nth-child(3) > .form-generate__items__label')
            .contains('配額單位')
        cy.get('.form-generate > .form-generate__content > :nth-child(4) > .form-generate__items__label')
            .contains('待複檢')
        cy.get('.form-generate > .form-generate__content > :nth-child(5) > .form-generate__items__label')
            .contains('到港日期')
        cy.get('.form-generate > .form-generate__content > :nth-child(6) > .form-generate__items__label')
            .contains('出庫時間')
    })
    it('依日期查詢', () => {
        cy.get(':nth-child(1) > .ivu-date-picker > .ivu-date-picker-rel > .ivu-input-wrapper > .ivu-input')
            .type(`${dateFormat(startDate, false)} - ${dateFormat(endDate, false)}`)
            .type('{enter}')
        cy.get('.form-generate > .form-generate__content > :nth-child(1) > .form-generate__items__label')
            .click()
        cy.get('.ivu-btn-primary')
            .click()
        cy.get('table')
            .should('be.visible')
    })
    it ('表格介面檢查', () => {
        cy.get('.ivu-table-header > table > thead > tr > :nth-child(2)')
            .contains('生產編號')
        cy.get('.ivu-table-header > table > thead > tr > :nth-child(3)')
            .contains('底盤編號')
        cy.get('.ivu-table-header > table > thead > tr > :nth-child(4)')
            .contains('QRcode')
        cy.get('.ivu-table-header > table > thead > tr > :nth-child(5)')
            .contains('建立日期')
        cy.get('.ivu-table-header > table > thead > tr > :nth-child(6)')
            .contains('配額單位')
        cy.get('.ivu-table-header > table > thead > tr > :nth-child(7)')
            .contains('停車區域')
        cy.get('.ivu-table-header > table > thead > tr > :nth-child(8)')
            .contains('車位識別碼')
        cy.get('.ivu-table-header > table > thead > tr > :nth-child(9)')
            .contains('待複檢')
        cy.get('.ivu-table-header > table > thead > tr > :nth-child(10)')
            .contains('動作')
        cy.get('.m-search > :nth-child(2) > .btn > span')
            .contains('匯出')
    })
})