describe('查詢', () => {
    it('訪問頁面', () => {
        cy.visit('/frontend')
        cy.get('#menu-item-1 > .c-menu__items__title')
        .click()
    })
    it('介面檢查', () => {
        cy.get(':nth-child(1) > .form-generate__items__label')
            .contains('停車區域')
        cy.get(':nth-child(2) > .form-generate__items__label')
            .contains('車位識別碼')
    })
    it('查詢', () => {
        cy.get('.ivu-btn-primary')
            .click()
    })
    it ('表格介面檢查', () => {
        cy.get('.ivu-table-header > table > thead > tr > :nth-child(1)')
            .contains('車位識別碼')
        cy.get('.ivu-table-header > table > thead > tr > :nth-child(2)')
            .contains('停車區域')
        cy.get('.ivu-table-header > table > thead > tr > :nth-child(3)')
            .contains('使用中')
        cy.get('.ivu-table-header > table > thead > tr > :nth-child(4)')
            .contains('生產編號')
        cy.get('.ivu-table-header > table > thead > tr > :nth-child(5)')
            .contains('底盤編號')
        cy.get('.ivu-table-header > table > thead > tr > :nth-child(6)')
            .contains('QRcode')
        cy.get('.ivu-table-header > table > thead > tr > :nth-child(7)')
            .contains('動作')
        cy.get('.m-search > :nth-child(2) > .btn > span')
            .contains('匯出')
    })
})