describe('使用者', () => {
    it('訪問頁面', () => {
        cy.visit('/frontend/ins/config')
        cy.get('.m-config-system-user')
            .should('be.visible')
    })
    it('介面元件初始', () => {
        cy.get('.tools-right > .btn')
            .contains('新增使用者')
        cy.get('.tools-left__search > input')
            .should('have.attr', 'placeholder', '快速查詢...')
        cy.get('.list')
            .should('be.visible')
    })
    it('新增使用者', () => {
        cy.get('.tools-right > .btn')
            .click()
        cy.get('.add-user-modal > .ivu-modal-wrap > .ivu-modal > .ivu-modal-content > .ivu-modal-header')
            .should('be.visible')
    })
    it('未輸入使用者提醒', () => {
        cy.get(':nth-child(2) > .ivu-form-item-content > .ivu-poptip > .ivu-poptip-rel > .w-250 > .ivu-input')
            .type(' ')
            .clear()
            .click()
        cy.get(':nth-child(2) > .ivu-form-item-content > .ivu-form-item-error-tip')
            .contains('使用者名稱為必填')
        cy.get('.ivu-modal-body > .form > :nth-child(1)')
            .click()
    })
    it('未輸入密碼提醒', () => {
        cy.get(':nth-child(4) > .ivu-form-item-content > .ivu-poptip > .ivu-poptip-rel > .w-250 > .ivu-input')
            .type(' ')
            .clear()
            .click()
        cy.get(':nth-child(4) > .ivu-form-item-content > .ivu-form-item-error-tip')
            .contains('請輸入密碼')
        cy.get('.ivu-modal-body > .form > :nth-child(3)')
            .click()
    })
    it('未輸入確認密碼提醒', () => {
        cy.get(':nth-child(6) > .ivu-form-item-content > .ivu-poptip > .ivu-poptip-rel > .w-250 > .ivu-input')
            .type(' ')
            .clear()
            .click()
        cy.get(':nth-child(6) > .ivu-form-item-content > .ivu-form-item-error-tip')
            .contains('請再次輸入密碼')
    })
    it('密碼需介於 8-16 碼之間', () => {
        cy.get(':nth-child(4) > .ivu-form-item-content > .ivu-poptip > .ivu-poptip-rel > .w-250 > .ivu-input')
            .type('123')
        cy.get(':nth-child(4) > .ivu-form-item-content > .ivu-form-item-error-tip')
            .contains('密碼不得少於8碼')
        cy.get(':nth-child(4) > .ivu-form-item-content > .ivu-poptip > .ivu-poptip-rel > .w-250 > .ivu-input')
            .clear()
            .type('11111111111111111')
        cy.get(':nth-child(4) > .ivu-form-item-content > .ivu-form-item-error-tip')
            .contains('密碼不得大於16碼')
    })
    it('密碼需含一個以上的英文字', () => {
        cy.get(':nth-child(4) > .ivu-form-item-content > .ivu-poptip > .ivu-poptip-rel > .w-250 > .ivu-input')
            .clear()
            .type('12345678')
        cy.get(':nth-child(4) > .ivu-form-item-content > .ivu-form-item-error-tip')
            .contains('密碼至少輸入一個英文字')
    })
    it('確認密碼驗證', () => {
        cy.get(':nth-child(6) > .ivu-form-item-content > .ivu-poptip > .ivu-poptip-rel > .w-250 > .ivu-input')
            .type('1234567')
        cy.get(':nth-child(6) > .ivu-form-item-content > .ivu-form-item-error-tip')
            .contains('新舊密碼不同')
    })
    it('新增使用者', () => {
        cy.get(':nth-child(2) > .ivu-form-item-content > .ivu-poptip > .ivu-poptip-rel > .w-250 > .ivu-input')
            .clear()
            .type('e2eTest')
        cy.get(':nth-child(4) > .ivu-form-item-content > .ivu-poptip > .ivu-poptip-rel > .w-250 > .ivu-input')
            .clear()
            .type('Fuco1234')
        cy.get(':nth-child(6) > .ivu-form-item-content > .ivu-poptip > .ivu-poptip-rel > .w-250 > .ivu-input')
            .clear()
            .type('Fuco1234')
        cy.get('.ivu-modal-footer > div > :nth-child(3)')
            .click()
        cy.get('.list')
            .contains('e2eTest')
        cy.get('.p-index > .content')
            .scrollTo('top')
        cy.wait(2000)
    })
    it('變更使用者名稱與設定使用者權限', () => {
        cy.get('.list')
            .children()
            .then(data => {
                let index = 0
                for (let i = 0; i < data.length; i++)
                    if (data[i].childNodes[0].childNodes[0].innerText === 'e2eTest') index = i + 1

                cy.get(':nth-child(' + index + ') > .list-items__menu > .list-items__menu__container')
                    .trigger('mouseover')
                cy.get(':nth-child(' + index + ') > .list-items__menu > .list-items__menu__container > :nth-child(1)')
                    .click()
                cy.get('.ivu-modal-wrap > .ivu-modal > .ivu-modal-content > .ivu-modal-header > .fz--large')
                    .contains('變更使用者')
                cy.get('.ivu-tooltip-rel > .form-input > .ivu-input')
                    .clear()
                    .type('e2e', { force: true })
                cy.get(':nth-child(4) > .ivu-form-item > .ivu-form-item-content > .form-input > .ivu-input')
                    .clear({ force: true })
                    .type('Test', { force: true })
                cy.get(':nth-child(7) > .ivu-form-item > .ivu-form-item-content > .form-input > .ivu-input')
                    .clear({ force: true })
                    .type('test@email.com', { force: true })
                cy.get('.checkbox > :nth-child(2) > .ivu-checkbox-wrapper')
                    .click({ force: true })
                cy.get('.m-config-user-modal > .ivu-modal > .ivu-modal-content > .ivu-modal-footer > div > :nth-child(2)')
                    .click({ force: true })
                cy.wait(1000)
                cy.get('.list')
                    .children()
                    .then(data => {
                        let hasChanged = false
                        for (let i = 0; i < data.length; i++)
                            if (data[i].childNodes[0].childNodes[0].childNodes[1].innerText === 'e2e') hasChanged = true

                        if (!hasChanged) throw new Error('使用者名稱變更失敗')
                    })
            })
        cy.wait(2000)
    })
    it('刪除使用者', () => {
        cy.get('.list')
            .children()
            .then(data => {
                let index = 0
                for (let i = 0; i < data.length; i++)
                    if (data[i].childNodes[0].childNodes[0].innerText === 'e2e') index = i + 1

                cy.get(':nth-child(' + index + ') > .list-items__menu > .list-items__menu__container')
                    .trigger('mouseover')
                cy.get(':nth-child(' + index + ') > .list-items__menu > .list-items__menu__container > :nth-child(2)')
                    .click()
                cy.get(':nth-child(8) > .ivu-modal-wrap > .ivu-modal > .ivu-modal-content > .ivu-modal-header > .fz--large')
                    .contains('刪除確認')
                cy.get('.btn--error')
                    .click()
            })
            .then(data => {
                for (let i = 0; i < data.length; i++)
                    if (data[i].childNodes[0].innerText === 'e2e') throw new Error('使用者刪除失敗')
            })
    })
})